apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-grafana-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-grafana-app
  template:
    metadata:
      labels:
        app: flask-grafana-app
    spec:
      containers:
      - name: flask-grafana-app
        image: flask-grafana-app:v1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-grafana-app
spec:
  selector:
    app: flask-grafana-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort